version: 2.1
jobs:
  build:
    working_directory: ~/git-machete-intellij-plugin
    docker:
      - image: openjdk:11

    steps:
      - checkout
      - run:
          name: Check formatting
          command: |
            ./gradlew spotlessCheck
      - run:
          name: Install pip3
          command: |
            cat /etc/os-release
            lsb_release -a
            hostnamectl
            apt-get update
            apt-get -y install python3-pip
      - run:
          name: Install machete CLI
          command: |
            pip3 install --user git-machete==2.12.5
      - run:
          name: Build & Test
          command: |
            ./gradlew test
