version: 2.1
jobs:
  build:
    working_directory: ~/git-machete-intellij-plugin
    docker:
      - image: openkbs/jdk11-mvn-py3

    steps:
      - checkout
      - run:
          name: Prepare Build
          command: |
            set -x
            ./scripts/check-version-bump-on-prs
            ./scripts/check-wildcard-imports
            ./scripts/specify-snapshot-revision
      - run:
          name: Start Gradle Daemon
          command: |
            ./gradlew
      - run:
          name: Check Formatting
          command: |
            ./gradlew spotlessCheck
      - run:
          name: Install git-machete CLI
          command: pip3 install git-machete==2.12.5
      - run:
          name: Build & Test
          command: |
            ./gradlew test
      - store_test_results:
          path: backendRoot/build/test-results/
      - run:
          name: Build Plugin Artifact
          command: |
            ./gradlew intellijPlugin:buildPlugin
      - store_artifacts:
          path: ~/git-machete-intellij-plugin/intellijPlugin/build/distributions
          destination: .

