version: 2.1
jobs:
  build:
    working_directory: ~/git-machete-intellij-plugin
    docker:
      - image: gitmachete/intellij-plugin-ci

    steps:
      - checkout
      - run:
          name: Prepare build
          command: |
            set -x
            ./scripts/enforce-data-keys-javadoc-for-actions
            ./scripts/enforce-issue-number-for-todos
            ./scripts/enforce-newline-at-eof
            ./scripts/enforce-version-bump
            ./scripts/prohibit-trailing-whitespace
            ./scripts/specify-snapshot-revision

      - run:
          name: Start gradle daemon
          command: ./gradlew
      - run:
          name: Check formatting
          command: ./gradlew spotlessCheck
      - run:
          name: Compile production code
          # Given the RAM limits on CI (4GB), max-workers=2 is necessary to prevent OOMs.
          command: ./gradlew --max-workers=2 compileJava
      - run:
          name: Check Javadoc correctness
          command: ./gradlew javadoc
      - run:
          name: Run static code analyzer
          command: ./gradlew --warn checkstyleMain

      - run:
          name: Compile tests
          command: ./gradlew compileTestJava
      - run:
          name: Run tests
          command: ./gradlew test
      - store_test_results:
          path: backendRoot/build/test-results/

      - run:
          name: Build plugin artifact
          command: ./gradlew buildPlugin
      - run:
          name: Verify binary compatibility with supported IntelliJ versions
          command: |
            if [[ $CIRCLE_BRANCH == master ]]; then
              ./scripts/enforce-binary-compatibility
            else
              echo Skipping, not a master build
            fi
      - store_artifacts:
          path: frontendUi/build/distributions/
          destination: .
