version: 2.1
jobs:
  build:
    working_directory: ~/git-machete-intellij-plugin
    docker:
      - image: gitmachete/intellij-plugin-ci

    steps:
      - checkout
      - run:
          name: Prepare build
          command: |
            set -x
            ./scripts/enforce-issue-number-for-todos
            ./scripts/enforce-version-bump
            ./scripts/prohibit-trailing-whitespace
            ./scripts/prohibit-wildcard-imports
            ./scripts/specify-snapshot-revision

      - run:
          name: Start gradle daemon
          command: ./gradlew
      - run:
          name: Check formatting
          command: ./gradlew spotlessCheck
      - run:
          name: Static code analyzer
          command: ./gradlew spotbugsMain
      - run:
          name: Build & test
          command: ./gradlew test
      - store_test_results:
          path: backendRoot/build/test-results/

      - run:
          name: Build plugin artifact
          command: ./gradlew buildPlugin
      - store_artifacts:
          path: ~/git-machete-intellij-plugin/frontend/build/distributions/
          destination: .
