version: 2.1
jobs:
  build:
    working_directory: ~/git-machete-intellij-plugin
    docker:
      - image: openkbs/jdk11-mvn-py3

    steps:
      - checkout
      - run:
          name: Check formatting
          command: |
            ./gradlew spotlessCheck
      - run:
          name: Install machete CLI
          command: pip3 install git-machete==2.12.5
      - run:
          name: Build & Test
          command: |
            ./gradlew test
