version: 2.1
jobs:
  build:
    working_directory: ~/git-machete-intellij-plugin
    docker:
      - image: openjdk:11

    steps:
      - checkout
      - run:
          name: Check formatting
          command: |
            ./gradlew spotlessCheck
      - run:
          name: Install pip3
          command: |
            apt update
            apt -y install python3-pip
      - run:
          name: Install machete CLI
          command: pip3 install --system git-machete==2.12.5
      - run:
          name: Prepare repository from script
          command: |
            mkdir /var/tmp/machete-tests
            /bin/bash ~/git-machete-intellij-plugin/backendRoot/src/test/resources/repo1.sh /var/tmp/machete-tests
      - run:
          name: Build & Test
          command: |
            ./gradlew test
